# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
# - script: /usr/local/bin/pod install
#   displayName: 'pod install using a script'
# 
# - task: CocoaPods@0
#   displayName: 'pod install using the CocoaPods task with defaults'
# 
# - task: CocoaPods@0
#   inputs:
#     forceRepoUpdate: true
#     projectDirectory: '$(system.defaultWorkingDirectory)'
#   displayName: 'pod install using the CocoaPods task with a forced repo update and a custom project directory'
  
- task: Xcode@5
  inputs:
    actions: 'test'
    scheme: 'TestAppTests'
    sdk: 'iphoneos'
    configuration: 'Debug'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
    destinationPlatformOption: 'iOS' # Optional. Options: default, iOS, tvOS, macOS, custom
    destinationPlatform: 'iOS' # Optional
    destinationTypeOption: 'simulators' # Optional. Options: simulators, devices
    destinationSimulators: 'iPhone 11' # Optional
    destinationDevices: 'iPhone 11' # Optional
    useXcpretty: true

    